### ISSUE TITLE
Images in a slides plugin flicker all the time in BookBlock

### ISSUE THREAD

**Issue by bluishoul** [codrops/BookBlock#28]
I try to use [slides.js](http://slidesjs.com) to add feature of mutiple-image gallary in bookblock pages,but when I turn the page,the right part of the page which contains a slides will flicker,and the left part of the page would not.

Then I try another slides plugin  [responsiveslides.js](https://github.com/viljamis/ResponsiveSlides.js),the problem is still there,I guess maybe that's the bug of bookblock.

Behaves OK: in firefox,
Flicker : in chrome , safari of iPad

**Comment by Kembreg** [comment]
Having a similar issue with bookblock.  Generating the first image right away, initiating the plugin and then in the background generating another 10 images. (All from a PDF, 2 seconds each, hence the need to do only 1 up front).

Because the other images did not exist when the plugin was initiated, the plugin will not recognize them.

Need to find a way to re-initiate the plugin.  Or clear it and initiate it again.
Any ideas?

**Comment by gabrielbdf** [comment]
Trying to add this code before bookblock calling

Check if device is IOS and add translateZ to zero to prevent transform flicker
`			if (iOS()) {
				$('head').append("<style>.bb-page { -webkit-transform: translateZ(0); }</style>");
			}`


Function to check

` function iOS() {

	var iDevices = [
		'iPad Simulator',
		'iPhone Simulator',
		'iPod Simulator',
		'iPad',
		'iPhone',
		'iPod'
	];

	if (!!navigator.platform) {
		while (iDevices.length) {
			if (navigator.platform === iDevices.pop()) { return true; }
		}
	}

	return false;
} `
